#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snapshot-webui
  namespace: galasa-tekton
spec:
  resources:
  - name: git-tekton
    type: git
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
  tasks:
  - name: snapshot-boot-embedded
    taskRef:
      name: snapshot-generic
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-webui-amd64
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
