#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
#  generateName: main-webui-
  name: main-webui
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  pipelineRef:
    name: webui-repo-build
  serviceAccountName: build-bot
  resources:
  - name: git-webui
    resourceRef:
      name: git-webui-main
  - name: git-framework
    resourceRef:
      name: git-framework-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
